# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNW_S4J_lRQGSifc_ngKC5Wvl6K_mUUA

# Task
Build a depression prediction model using the `depression_dataset_reddit_cleaned.csv` file, train a Logistic Regression model, evaluate its performance, and provide an interactive interface to predict depression scores from user input text.

## Load Dataset and Initial Preprocessing

### Subtask:
Load the 'depression_dataset_reddit_cleaned.csv' file into a pandas DataFrame. Perform initial text cleaning by converting text to lowercase, removing punctuation, and extra whitespace. This step will use the file path you provided.

**Reasoning**:
First, I'll import the pandas library to work with DataFrames. Then, I'll load the specified CSV file into a DataFrame. After loading, I will apply the text cleaning operations as requested: converting text to lowercase, removing punctuation, and stripping extra whitespace from the 'text' column. Finally, I'll display the first few rows and information about the DataFrame to verify the loading and initial cleaning steps.
"""

import pandas as pd
import string

# Load the dataset
df = pd.read_csv('/content/depression_dataset_reddit_cleaned.csv')

# Convert text to lowercase
df['text'] = df['text'].str.lower()

# Remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
df['text'] = df['text'].apply(remove_punctuation)

# Remove extra whitespace
df['text'] = df['text'].str.strip().str.replace('\s+', ' ', regex=True)

# Display the first few rows of the cleaned DataFrame and its info
print("DataFrame head after initial cleaning:")
print(df.head())
print("\nDataFrame info after initial cleaning:")
df.info()

"""**Reasoning**:
The previous code failed because the column name 'text' was not found in the DataFrame. Based on the kernel state, the correct column to clean is 'clean_text'. I will modify the code to use the 'clean_text' column for all text processing operations.


"""

import pandas as pd
import string

# Load the dataset
df = pd.read_csv('/content/depression_dataset_reddit_cleaned.csv')

# Convert text to lowercase
df['clean_text'] = df['clean_text'].str.lower()

# Remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
df['clean_text'] = df['clean_text'].apply(remove_punctuation)

# Remove extra whitespace
df['clean_text'] = df['clean_text'].str.strip().str.replace('\s+', ' ', regex=True)

# Display the first few rows of the cleaned DataFrame and its info
print("DataFrame head after initial cleaning:")
print(df.head())
print("\nDataFrame info after initial cleaning:")
df.info()

"""**Reasoning**:
The previous code produced a `SyntaxWarning` regarding an invalid escape sequence in the `str.replace` method. To resolve this, I will use a raw string literal `r'\s+'` for the regular expression pattern.


"""

import pandas as pd
import string

# Load the dataset
df = pd.read_csv('/content/depression_dataset_reddit_cleaned.csv')

# Convert text to lowercase
df['clean_text'] = df['clean_text'].str.lower()

# Remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))
df['clean_text'] = df['clean_text'].apply(remove_punctuation)

# Remove extra whitespace
df['clean_text'] = df['clean_text'].str.strip().str.replace(r'\s+', ' ', regex=True)

# Display the first few rows of the cleaned DataFrame and its info
print("DataFrame head after initial cleaning:")
print(df.head())
print("\nDataFrame info after initial cleaning:")
df.info()

"""## TF-IDF Vectorization and Data Splitting

### Subtask:
Apply TF-IDF vectorization to the cleaned text data to convert it into numerical features. Then, split the dataset into training and testing sets to prepare for model training and evaluation.

**Reasoning**:
I will import the necessary libraries, initialize the TF-IDF vectorizer, transform the text data into features, and then split the data into training and testing sets as per the instructions.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=5000) # Limiting features to 5000 for practicality

# Fit and transform the 'clean_text' column
X = tfidf_vectorizer.fit_transform(df['clean_text'])
y = df['is_depression']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Train Logistic Regression Model

### Subtask:
Train a Logistic Regression model using the TF-IDF vectorized training data. The model will be configured for fast training, suitable for small GPU sizes, even if it means slightly less accuracy.

**Reasoning**:
I will import `LogisticRegression` from `sklearn.linear_model`, instantiate it with `solver='saga'`, `max_iter=1000`, and `n_jobs=-1` for fast training, and then fit the model using the `X_train` and `y_train` datasets.
"""

from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression model for fast training
# solver='saga' supports multinomial loss and L1/L2 regularization with parallelization
# max_iter is increased to help with convergence, though 1000 should be sufficient for many datasets
# n_jobs=-1 uses all available CPU cores for parallelization, speeding up training
model = LogisticRegression(solver='saga', max_iter=1000, n_jobs=-1, random_state=42)

# Train the model
model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

"""## Evaluate Model Accuracy

### Subtask:
Evaluate the trained Logistic Regression model's accuracy on the test set and print the result to understand its performance.

**Reasoning**:
I will import the `accuracy_score` function, make predictions on the test set using the trained model, calculate the accuracy, and then print the result as a percentage to evaluate the model's performance.
"""

from sklearn.metrics import accuracy_score

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print(f"Model Accuracy on the test set: {accuracy:.2%}")

"""## Define Scoring and Categorization Functions

### Subtask:
Implement functions to convert the model's predicted probabilities into a depression score (0-100) and categorize these scores into 'Low', 'Moderate', or 'High' depression levels based on predefined thresholds.

**Reasoning**:
I will define two Python functions as per the instructions: one to convert a probability to a depression score out of 100, and another to categorize this score into 'Low', 'Moderate', or 'High' levels with specified thresholds. Both functions will include comprehensive docstrings.
"""

def predict_and_score(probability):
    """
    Converts a depression probability (0-1) into a depression score (0-100).

    Args:
        probability (float): The predicted probability of depression, a value between 0 and 1.

    Returns:
        int: A depression score on a scale of 0 to 100.
    """
    return int(probability * 100)

def categorize_depression_level(score):
    """
    Categorizes a depression score (0-100) into 'Low', 'Moderate', or 'High' levels.

    Args:
        score (int): The depression score, an integer between 0 and 100.

    Returns:
        str: The categorized depression level ('Low', 'Moderate', or 'High').
    """
    if 0 <= score <= 33:
        return 'Low'
    elif 34 <= score <= 66:
        return 'Moderate'
    elif 67 <= score <= 100:
        return 'High'
    else:
        return 'Invalid Score'

print("Functions `predict_and_score` and `categorize_depression_level` have been defined.")

"""## Save Trained Model and Vectorizer

### Subtask:
Save the trained Logistic Regression model and the TF-IDF vectorizer as separate ".pkl" files. This ensures that the best model can be reused without retraining and the vectorizer is preserved for consistent preprocessing of new inputs.

**Reasoning**:
To save the trained model and vectorizer, I will import the `joblib` library and use its `dump` function to serialize both objects into `.pkl` files, then print a confirmation message.
"""

import joblib

# Save the trained Logistic Regression model
joblib.dump(model, 'logistic_regression_model.pkl')

# Save the TF-IDF vectorizer
joblib.dump(tfidf_vectorizer, 'tfidf_vectorizer.pkl')

print("Logistic Regression model and TF-IDF vectorizer saved successfully.")

"""## Interactive Prediction Function

### Subtask:
Create a function that takes user input text, preprocesses it using the saved TF-IDF vectorizer, uses the saved Logistic Regression model to predict the depression probability, converts it to a score, and categorizes it into a depression level. This function will then display the score and level.

**Reasoning**:
I need to import joblib to load the saved model and vectorizer, then define the `predict_depression` function that preprocesses the input text, vectorizes it, predicts the probability, converts it to a score and category, and finally prints the results.
"""

import joblib
import string

# Load the saved model and vectorizer
loaded_model = joblib.load('logistic_regression_model.pkl')
loaded_vectorizer = joblib.load('tfidf_vectorizer.pkl')

def predict_depression(user_input_text):
    """
    Predicts the depression score and level for a given user input text.

    Args:
        user_input_text (str): The text input from the user.

    Returns:
        None: Prints the depression score and level directly.
    """
    # Preprocess the user input text
    processed_text = user_input_text.lower()
    processed_text = processed_text.translate(str.maketrans('', '', string.punctuation))
    processed_text = processed_text.strip().replace(r'\s+', ' ', regex=True)

    # Transform the preprocessed text using the loaded TF-IDF vectorizer
    text_vectorized = loaded_vectorizer.transform([processed_text])

    # Predict the probability of depression using the loaded model
    # predict_proba returns probabilities for both classes (0 and 1). We need the probability of class 1.
    depression_probability = loaded_model.predict_proba(text_vectorized)[0][1]

    # Convert probability to a depression score (0-100)
    depression_score = predict_and_score(depression_probability)

    # Categorize the depression level
    depression_level = categorize_depression_level(depression_score)

    print(f"\nUser Input: '{user_input_text}'")
    print(f"Depression Probability: {depression_probability:.2f}")
    print(f"Depression Score (0-100): {depression_score}")
    print(f"Depression Level: {depression_level}")

print("Interactive prediction function `predict_depression` has been defined.")

"""## User Input and Prediction Loop

### Subtask:
Implement an interactive loop that continuously prompts the user for text input. For each input, it will call the prediction function to display the depression score and level, allowing users to test the model dynamically.

**Reasoning**:
I will implement an interactive loop using `while True` to continuously take user input, call the `predict_depression` function with the input, and break the loop if the user types 'exit'.
"""

print("\n--- Depression Prediction Interactive Tool ---")
print("Type 'exit' to quit at any time.")

while True:
    user_text = input("\nEnter text to predict depression level (or type 'exit' to quit): ")

    if user_text.lower() == 'exit':
        print("Exiting depression prediction tool. Goodbye!")
        break
    elif not user_text.strip():
        print("Input cannot be empty. Please enter some text.")
        continue

    predict_depression(user_text)

"""**Reasoning**:
The previous code failed because the built-in `str.replace()` method does not accept the `regex=True` argument. To fix this, I need to use the `re.sub()` function from the `re` module for regular expression replacement on a string, and remove the `regex=True` argument from the `replace` call, which is not needed when using `re.sub()`.


"""

import joblib
import string
import re

# Load the saved model and vectorizer
loaded_model = joblib.load('logistic_regression_model.pkl')
loaded_vectorizer = joblib.load('tfidf_vectorizer.pkl')

def predict_depression(user_input_text):
    """
    Predicts the depression score and level for a given user input text.

    Args:
        user_input_text (str): The text input from the user.

    Returns:
        None: Prints the depression score and level directly.
    """
    # Preprocess the user input text
    processed_text = user_input_text.lower()
    processed_text = processed_text.translate(str.maketrans('', '', string.punctuation))
    # Use re.sub for regex replacement on a string, as str.replace does not support regex=True
    processed_text = re.sub(r'\s+', ' ', processed_text.strip())

    # Transform the preprocessed text using the loaded TF-IDF vectorizer
    text_vectorized = loaded_vectorizer.transform([processed_text])

    # Predict the probability of depression using the loaded model
    # predict_proba returns probabilities for both classes (0 and 1). We need the probability of class 1.
    depression_probability = loaded_model.predict_proba(text_vectorized)[0][1]

    # Convert probability to a depression score (0-100)
    depression_score = predict_and_score(depression_probability)

    # Categorize the depression level
    depression_level = categorize_depression_level(depression_score)

    print(f"\nUser Input: '{user_input_text}'")
    print(f"Depression Probability: {depression_probability:.2f}")
    print(f"Depression Score (0-100): {depression_score}")
    print(f"Depression Level: {depression_level}")

print("Interactive prediction function `predict_depression` has been defined.")

"""**Reasoning**:
The `predict_depression` function has been redefined with the fix. Now, I will re-run the interactive loop to allow the user to test the model dynamically and confirm that the `TypeError` is resolved.


"""

print("\n--- Depression Prediction Interactive Tool ---")
print("Type 'exit' to quit at any time.")

while True:
    user_text = input("\nEnter text to predict depression level (or type 'exit' to quit): ")

    if user_text.lower() == 'exit':
        print("Exiting depression prediction tool. Goodbye!")
        break
    elif not user_text.strip():
        print("Input cannot be empty. Please enter some text.")
        continue

    predict_depression(user_text)

"""## Final Task

### Subtask:
Summarize the model's performance and demonstrate its interactive use, providing the user with the ability to test new text inputs.

## Summary:

### Data Analysis Key Findings

*   **Data Preprocessing:** The `depression_dataset_reddit_cleaned.csv` was successfully loaded and cleaned. This involved converting text to lowercase, removing punctuation, and standardizing whitespace. An initial `KeyError` for 'text' was resolved by using the correct 'clean\_text' column, and a `SyntaxWarning` for `\s+` in `str.replace` was fixed by switching to raw string literals (`r'\s+'`) or `re.sub`.
*   **Feature Engineering:** TF-IDF vectorization was applied to the cleaned text, creating a feature matrix `X` with 5000 features. The dataset was then split into training and testing sets, resulting in `X_train` with 6184 samples, `X_test` with 1547 samples, `y_train` with 6184 labels, and `y_test` with 1547 labels.
*   **Model Training:** A Logistic Regression model was trained using the `saga` solver, `max_iter=1000`, and `n_jobs=-1` for efficient training.
*   **Model Performance:** The trained Logistic Regression model achieved an accuracy of 95.48% on the test set.
*   **Prediction and Categorization Logic:** Functions were defined to convert predicted probabilities into a depression score (0-100) and categorize these scores into 'Low' (0-33), 'Moderate' (34-66), or 'High' (67-100) depression levels.
*   **Persistence:** The trained Logistic Regression model and the TF-IDF vectorizer were saved as `logistic_regression_model.pkl` and `tfidf_vectorizer.pkl`, respectively, for later reuse.
*   **Interactive Tool Development:** An interactive prediction function was created that preprocesses user input, vectorizes it, predicts the depression probability, converts it to a score, and categorizes it. An initial `TypeError` with `str.replace` during text preprocessing in the interactive function was resolved by using `re.sub` for regular expression-based whitespace removal. The interactive loop allows users to input text and receive real-time predictions or exit gracefully.

### Insights or Next Steps

*   The model demonstrates high accuracy (95.48%), suggesting strong predictive capability for depression detection based on text data, which is promising for initial screening applications.
*   For deployment, integrating this interactive tool into a web application or a more user-friendly interface would enhance accessibility and practical use.
"""